export {default as Home} from './Home'
export {default as CommunityDetail} from './CommunityDetail'
export {default as Submit} from './Submit'
export {default as PostDetail} from './PostDetail'
export {default as SavedPosts} from './SavedPosts'
export {default as Profile} from './Profile'
export {default as SearchPage} from './SearchPage'
export {default as WorkshopsPage} from './WorkshopsPage'